version: '3.8'

services:
  email-api:
    build: .
    container_name: email-api
    restart: always
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - app-network

  worker:
    build: .
    deploy:
      replicas: 3
    restart: always
    env_file: .env
    command: ["node", "src/worker.js"]
    depends_on:

      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass sua_senha_redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
